### ISSUE TITLE
First screen is indexed as 0th while creating conditional questionnaires

### ISSUE THREAD

**Issue by anirudh4792** [ChildMindInstitute/mindlogger-app#59] opened 2019-01-08 10:48 UTC

**Comment by anirudh4792** [comment] 2019-01-08 10:54
First screen has a question - what day is it today (response 1: Mon, response 2: Tue). 'If response 1, go to screen 2 and if response 2, go to screen 3....'
select response 1 and it goes to screen 3, response 2 and the app hangs, . It works 'if response 1, go to screen 1......'
Could be that the first screen is the home screen and the label screen 1 indicates the screen below and not the one above

**Comment by shnizzedy** [comment] 2019-01-08 15:12
Duplicate of https://github.com/ChildMindInstitute/mindlogger-app-admin-panel/issues/47

**Comment by binarybottle** [comment] 2019-06-07 02:36
(Duplicate issue, as noted above.)

**Closed** 2019-06-07 02:35 UTC
Labels: bug
