### ISSUE TITLE
A/B Trails 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#1775] opened 2021-05-20 10:20 UTC
As an admin, I want an applet that contains an A/B Trail so that I can evaluate a user's ability to connect numbers and letters by drawing a line between them in ascending order. 

Requirements
- Objective of feature: Display 2 screens that require the user to draw a line between ascending numbers(screen 1) and if the user passes that require the user to draw a line between ascending numbers and letters ( 1 -> A -> 2 -> B -> etc) 
- If the user does not connect in the right order, then the system displays an error and requires the user to start again from the last correct connection
- The user cannot progress to the second page/ finish the activity unless the correct order is achieved by the user 
- The amount of time the user takes to complete each trail (test screen) is recorded data and the number of errors the user had for each 
- The user should only have 5 minutes to complete the entire activity 
** If the user does not complete the assessment in 5 minutes, record the amount of time it took to complete the 1st and second screen and the number of errors the user had. Then display the thank you page to the user 
- We need to show this working in mobile and a way to export it on admin
- Ensure that the data export shows errors at each pixel if the user connects to the wrong next option or stops and lifts pen off-screen 
** E0 = Correct path (User went from point 1 to point 2) 
** E1 = Incorrect Path (User went from point 1 to point 8) 
** E2 = Path stopped (User went from point 1 stopped and lifted pen from screen)
- If user has E1 happen, then the incorrect dot the user landed on flashes red, the line is erased between that point and the last correct point and then the last correct point flashes green 
- If the user has E2 happen, then the line is erased to the last correct point and that correct point flashes green

Up to 4:20 on [this video ](https://www.youtube.com/watch?v=ybnhZCQ_Ji0) shows a paper version of the same process. 

[ Requirements here](https://docs.google.com/document/d/1pwjqubcpHaQJX_YFDskEyD2U4pJ99zse_x-mj_nJ55g/edit?usp=sharing)

**Comment by WorldImpex** [comment] 2021-10-12 14:20
1. The data output does not appear to match the specs in the Trails A/B document. It looks like we just get a generic start and stop time for the task. But these data might be hidden in the "value: [object Object]" cell of the CSV export, maybe? We need the full x,y,t with annotations for error for each sampled point; you had already implemented this type of reporting a while back in the drawing canvas. 
2. Task stimuli do not match the layout of the trails stimuli that we provided. The point of doing this task in this way in MoBI is to replicate the traditional task but take advantage of the drawing features of MindLogger and multimodal readouts of MoBI
3. The stimuli are not appropriately scaled for the iPad. All stimuli are compressed into the top left 1/3 of the canvas. 
4. The task display only shows straight lines, and does not appear to be tracking the stylus position. 
5. You have to pick up the stylus to end the line, which the instructions for the task explicitly discourages, except in the case of an error. Users need to be able to draw continuously as in the instructions and original task. 
6. When initiating a line after making a correct connection and lifting the stylus, it is often difficult to get the app to recognize the stylus has touched once again inside a circle.
7. Likewise, registering the termination of a line within the circle appears quite finicky. I didn’t try to confirm with video, but several times it seemed as though I lifted the stylus within the circle but it was not registered unless I was very close to the center of the ROI. Maybe both this and item 6 are just a function of a too small region of interest for the targets.  This might also be less of a problem when the stimuli are scaled to fit the iPad appropriately.
8. No detection of the stylus intersecting with incorrect targets. These should be reflected as errors. 
9. Readability of the stimuli is not good. The outlined numbers and letters inside the circle are hard to read, and the outline feature of the font does not appear to be used in any way. Use a filled-in font.

**Comment by natalia-muzyka** [comment] 2021-12-09 13:02
@Matchdev120 @WorldImpex could anyone share the applet schema, please?

**Comment by WorldImpex** [comment] 2021-12-09 13:26
Done!

**Comment by WorldImpex** [comment] 2021-12-10 20:17
Initial feedback: 
1. Export has millisecond precision
2. Add "Click next to start" at the end of each instructional video 
3. Add "Finished. Click next to continue." when the user completes each task 
4. If user hits the wrong circle turn it green so the user knows to start from there. Green should disappear after the user resumes

**Comment by Matchdev120** [comment] 2021-12-13 13:57
@Wil Would you explain 1) (the millisecond precision) a little more?

**Comment by natalia-muzyka** [comment] 2021-12-13 13:58
**from the @WorldImpex comment:**

1. Detailed export is missing: 
https://www.screencast.com/t/5dxqxdho7Mi
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/f08321e1-b702-4582-85b0-1f9866b1b29e)

2. Tasks do not match the provided assets (question: should they be exactly the same or just similar?)
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/a3c3b510-cd68-42cf-b6f7-01f71f6f2562)

3. Text is missing(overlapped by canvas) on iPad and Android tablet, as well as in the landscape mode on Android phones:
Video: https://www.screencast.com/t/IjT3ngqfMyyW
Portrait: iPad Air 2 WiFi / iOS 14.6, Samsung Tab S6 / Android 9
Landscape: Samsung S7 / Android 8

4-8 Can't check Apple pen. On Samsung Tab S6 taps/stylus aren't recognized at all. 
https://www.screencast.com/t/144LhHZXS
If I use tap gesture the #6 is randomly reproducible:
https://www.screencast.com/t/tm6eeY6xLx

9 fixed

---

**What I've noticed:**

1.  Is there any defined timing for demo instructions? Instructions seem too fast, as for the user who doesn't read quick enough.

2. If the user has E2 happen, then the line is erased to the last correct point, this point flashes green only once. Then only the 1 is green. instead of:
Green Circle indicates last valid circle. User returns to last valid;  incorrect line remains User continues and green color removed.
What is the correct behavior? Doc says that incorrect lines remain on the screen, but in the ticket:
If user has E1 happen, then the incorrect dot the user landed on flashes red, the line is erased between that point and the last correct point and then the last correct point flashes green
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/8d64e1f7-6575-4057-81e7-d77ef8708999)

3. undo button doesn't do anything, shouldn't it be removed?

4. The user should only have 5 minutes to complete the entire activity -  how is this time divided by screens? Currently, Trail1/Trail2 (testA) isn't completed(stopped) after 150 seconds. Trail3/Trail4(testB) isn't completed after 300 seconds:
https://www.screencast.com/t/bSjyJkhdG9r

5. the beginning(#1) is always green (shouldn't every last response be colored with green as it is displayed in the instruction demo?)

6. When user lifts a finger the last correct point doesn't flash with green color:
https://www.screencast.com/t/pwVyMNWqA

7.  The Next button appears/disappears on trail1/trail2/trail3 screen right after proceeding to the screen:
 What is the correct behavior? Ticket says:

> The user cannot progress to the second page/ finish the activity unless the correct order is achieved by the user

Doc says:
![Screenshot 2021-12-13 155239.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/7bf73181-d29f-429a-b6f3-49cb6d5dc1b5)


8. on the latest instruction screen there is Done button when instruction is finished:
https://www.screencast.com/t/KEaarDPxnl

9. the straight line from the last correct point is appeared when user makes mistake, lift the finger, taps incorrect point and then correct point:
https://www.screencast.com/t/6b4Ls0OJKw

10. Android: after rotating the device instructions demo is restarted
https://www.screencast.com/t/xrA9dMhbSh

11. Samsung S7 / Android 8: crash after completing the activity:
https://www.screencast.com/t/YUEBq4D3D

**Comment by natalia-muzyka** [comment] 2021-12-14 08:11
@WorldImpex 

4. Test A = trail 2, test B = trail 4? So trail 1 and trail 3 are samples without any timing, right?

6. I've got it from the ticket (the last option). Do you mean it is not a requirement anymore?
"If the user has E2 happen, then the line is erased to the last correct point and that correct point flashes green"

7. Could you confirm, please, if I understand the requirement correctly?
It means that the Next button should appear only if user achieved the correct order before time is up. 
- Test A(trail 2) - If time is up (150 seconds), the current test screen should be automatically closed with recorded responses, the trail 3(sample B) should be opened.
- Test B(trail 4) - if time is up (300 seconds), activity should be ended (thanks screen is displayed), selected responses are recorded.

10. It is true for Android tablet as well. Or we should focus only on portrait version?

And another question: should the naming be trail1-trail4, or Sample A, Test A, Sample B, Test B? It is little bit confusing, looks like these all are different tests, but not a two pairs sample+test.

**Comment by WorldImpex** [comment] 2021-12-14 13:03
4. Yes 
5. It is a requirement if the user hits the incorrect point 
![image](https://user-images.githubusercontent.com/22243307/146001484-2159cdbd-c493-41b6-b2e4-97c12fe233ee.png)
6. Yes that is correct 
10. We can focus on portrait mode 

Additional - Yes I agree

**Comment by natalia-muzyka** [comment] 2021-12-15 11:54
@Matchdev120  is this a correct version of A/B trails? 
account: new16@test.org / abcd1234
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/d895de33-4b22-4340-b831-84991276baf0)

ML v0.18.16 staging

---

Samsung Tab S6 still doesn't recognize taps/pen and Samsung Tab S6 - App crashes on the activity screen (account new16@test.org / abcd1234): https://www.screencast.com/t/lrplXefurNPQ

Text is still missing in the demo and test screens on iPad and Samsung Tab S6: 
https://www.screencast.com/t/IjT3ngqfMyyW

---

**New issues:**

11. There is a timing issue. I always miss some demo or trails. 
E.g.: trail3(demo) is skipped. 
trail2(test) is automatically completed at ~1:20min and moved right to trail3(test)
Video:
iPhone 8 Plus (new16@test.org / abcd1234): https://www.screencast.com/t/qI1OJXtetMm
iPad Pro(samanyu3@vqsprint.com	/ 123456) : https://www.screencast.com/t/zerPJKk0

Activity is automatically closed on trail4(test) screen on ~2:40 min of entire activity (~1:20 of test B phase)
iPhone 8 Plus (test-email_1@1com.org	/ 123456): https://www.screencast.com/t/vPdifZHDx

12. Activity crashes after tapping on the incorrect point instead of "1" at the very beginning of the test:
https://www.screencast.com/t/DJY5hC2R2
iPad Pro 10.5 // iOS 15.0.2
iPhone 8 Plus // iOS 13.3
Samsung S7 // Android 8

13. Sometimes after restarting the activity the trail1 (test) screen is opened instead of demo, and after tapping on the "1" activity may crash:
https://www.screencast.com/t/pd1HSeVw
iPad Pro 10.5 // iOS 15.0.2
iPhone 8 Plus // iOS 13.3
Samsung S7 // Android 8

---

**From Initial feedback:**
1. Export has millisecond precision 
Not fixed - Export still doesn't reflect any data except start and end activity time.

2. Add "Click next to start" at the end of each instructional video
Fixed (checked on mobile)

3. Add "Finished. Click next to continue." when the user completes each task
Issue - @WorldImpex On the last test(trail 4) screen there should be click Done to complete or smth similar, I think
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/9961ca73-e6ab-4807-977d-0f45342f7070)

4. If user hits the wrong circle turn it green so the user knows to start from there. Green should disappear after the user resumes
@WorldImpex Somehow skipped this feedback. Want to clarify: Does this mean to turn in green the last correct circle if user lifted a pen/finger and then tapped the wrong circle?

**Comment by WorldImpex** [comment] 2021-12-15 14:48
3. Agreed @natalia-muzyka 
4. It would be if the user's next circle intersected was wrong then show the last correct circle turning green. It UI related to the user drawing to the next incorrect circle @natalia-muzyka

**Comment by natalia-muzyka** [comment] 2021-12-17 14:11
Assets don't match the requirements in this version.

**Fixed:**
Samsung Tab S6 doesn't recognize taps/pen and Samsung Tab S6 

Text is still missing in the demo and test screens on iPad and Samsung Tab S6:

Activity crashes after tapping on the incorrect point instead of "1" at the very beginning of the test:

Add "Finished. Click next to continue." when the user completes each task (last screen issue is fixed)

If user hits the wrong circle turn it green so the user knows to start from there. Green should disappear after the user resumes: https://www.screencast.com/t/RGUcJO0TvSl

---

**New issues:**
14. timing issue: 
trail 2 isn't closed after 150s: 
trail4 isn't closed after 300s: 


15. v1: there are two behaviors on trail 4 screen:
- "click Done to complete" info text is hidden too fast after completing the response:
https://www.screencast.com/t/3yIOxlYePF
- "click Done to complete" info text is displayed until the "done" btn isn't tapped, and after tapping DONE unnecessary info text(from the the trail4 demo) is displayed on the last screen 
https://www.screencast.com/t/8alJ2keT3Q1

16. if trail 1 was processed and closed, after resuming the activity the demo of the current trail is displayed: user can skip or watch the demo and selected responses will be displayed on the trail screen - in the export

17. v2: [UI] "begin" is overlapped by circle "3' on trail4

18. v2: headers trail1-trail4 instead of sample A, test A, sample B, test B

19. on iPad Air 2 / iOS 14.6 drawing is blocked, screen scrolls after an attempt to draw a line:
https://www.screencast.com/t/l6bVpa6e

20. report is missing info:
Timestamp for each x,y pair - relative to the start of the trial. - timestamp differs from other cognitive applets, is it correct displaying?
Number of errors + Annotations showing the x,y,t for errors on the forms - number of errors is 0 every time
(I'll add files after standup)

ML v0.18.19 staging
devices: 
iPhone 12 Pro Max	// iOS 15.0.1
iPad Pro 10.5 // iOS 15.0.2
Samsung Tab S6 // Android 9
Pixel 3XL // Android 10

**Comment by natalia-muzyka** [comment] 2021-12-17 17:26
Full export + video for #20:
https://drive.google.com/drive/folders/199G1mQz0AH1V73JTaikOuIaqrtBI8NQ4?usp=sharing

**Comment by jj105** [comment] 2021-12-17 17:37
20 - for timestamp, since it should be relative to start of trial I think it's correct that starting point has timestamp 0

**Comment by natalia-muzyka** [comment] 2021-12-20 10:06
@WorldImpex @Matchdev120 

- v2 assets don't match, they should be exactly the same if I understood the feedback correctly?
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/f0ce1612-098d-411a-953b-474553eccfe3)

- trail2(test A) and trail3(sample B) reports are equal: total time in the report is 3747 ms though completing test A took ~30 seconds, and completing sample B took ~6 seconds

- errors are still missing in the report: I made a mistake on sample A, test A, test B screens but they aren't reflected in the reports

video & report files: https://drive.google.com/drive/folders/1hHf64HipMcZZsyo1iKRyIBByTHOePkY5?usp=sharing

activity: A/B trails v2
new17@test.org	// abcd1234
ML v0.18.20 staging
iPad Pro 10.5 // iOS 15.0.2

**Comment by natalia-muzyka** [comment] 2021-12-20 16:57
Retested the export. 
@WorldImpex @jj105 

1. Looks like export doesn't reflect the next type of errors:
E2 = Path stopped (User went from point 1 stopped and lifted finger from the screen)
I made such a mistake on:
video #1 trail2(test A) screen
video #2 trail1(sample A) screen, trail4(test B) screen

2. the duplicate trail2 report issue is reproducible. Looks like it depends on what the trail will be opened in the particular moment, 'cause in one case(video 1) trail3 report is copied from trail2, and in another case (video 2), trail2 report is copied from trail3

3. there are no annotations for all the types of errors


videos + reports: https://drive.google.com/drive/folders/1MXuI9--AtO_zZOvNxrIKROXNnSO4NLzR?usp=sharing

**Comment by natalia-muzyka** [comment] 2021-12-21 11:25
@WorldImpex @Matchdev120 @jj105 

As I confirmed with Wil the Sample A and Sample B are ok to be displayed in this way (without adaptive width size), the main purpose is the correct displaying of Test A and Test B and distances between circles.
Current implementation of A/B trails:
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/c89e2066-e07e-4123-a821-0808f59613d4)

---

**Issues:**
- Noticed that in the case of E2 the line is not always erased, sometimes it remains on the screen (looks like it isn't erased when it has the correct direction and is close to the correct next point). And in this case, the E2 won't be defined in the report.
video 2: https://www.screencast.com/t/iNRdl0j6d2u
(please, pay attention, in the report is presented only one of two errors that I've made while drawing A~2)
report: https://drive.google.com/file/d/1iSeBzvlEP4jnYryyL4IOY0lMz7ZL15O9/view?usp=sharing

- Export: the duplicate trail2 report issue is reproducible. Looks like it depends on what the trail will be opened in the particular moment (~1:25), 'cause in one case trail3 report is copied from trail2, and in another case, trail2 report is copied from trail3

- If user taps the Incorrect point, this error isn't reflected in the report, and there is no type for such error in requirements (e0, e1, e2), so I assume that is expected? @WorldImpex 

- UI issue: Numbers and letters aren't vertically aligned
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/f36cf0c7-0d35-4266-bb08-99bd6812e18c)

videos + reports: https://drive.google.com/drive/folders/121_OqaFINZeVsByYtjTFDdzdi5lthenV?usp=sharing

activity: A/B trails v2
new17@test.org // abcd123
ML v0.18.20 staging
iPad Pro 10.5 // iOS 15.0.2

**Comment by natalia-muzyka** [comment] 2021-12-23 10:28
@Matchdev120 @WorldImpex  @jj105 

**Fixed:**
Duplicated reports for trail2 and trail3

**New issues:**
- After opening the Test A(trail2) or Test B(trail 4) screen, the demo(instructions) is restarted. In case if there were no huge delays in completing the samples. After clicking the Skip or Next, If user has already started drawing, previously created lines are displayed, but user isn't able to continue drawing. After start drawing from the very beginning, previous lines still remain on the screen and reflected in the report. 
Video: https://www.screencast.com/t/xQ3r0o9r
Correct behavior: When screen test A or test B is opened a second time, the timing works correctly: 
-- after the 150s test A screen is automatically closed and sample B demo is started (150s is started from the moment when user tapped the Next or Skip on the demo)
-- after the 300s test B screen is automatically closed, activity is completed, Thanks screen is displayed (300s is started from the moment when user tapped the Next or Skip on the demo)

- Within testing the timing: I draw a line without errors from 1 to 4 on the Test A screen. After 150s from the beginning of the trial, the next screen is opened. 
Issue: in the Test A report I see the E0 record from 4 to 5, though I didn't draw the line from 4 to 5. The same is reproducible on Test B screen: 
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/f905d427-66f9-4532-80c7-a84bc4273885)

videos + reports: https://drive.google.com/drive/folders/18xXvcRI9ocNA6jc73ZkDg3OHMyN8oHNi?usp=sharing

activity: A/B trails v2
new17@test.org // abcd123
ML v0.18.22 staging
iPad Pro 10.5 // iOS 15.0.2

---

**Questions:** 

1. In the report: Total time is always equal to the last coordinate timestamp and the first coordinate has always a 0 timestamp.
There can be such cases:
-- user starts drawing with a delay (not right after tapping the Next/Skip on the demo)
-- the screen was completed automatically because of the timing (150s or 300s)
In case#2 the timer starts after user tapped the Next/Skip on demo(instructions), so the report should record the Total time = max time(150s/300s), shouldn't it?
As per the requirements:
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/e6862864-662b-45d6-8936-d86550c712a6)

2. To make sure that this wasn't missed, is this the correct behavior or issue?: 
If user taps the Incorrect point, this error isn't reflected in the report

P.S. To not miss any of the questions/issues, I put everything here as well, thank you all for help in defining the requirements:
https://docs.google.com/spreadsheets/d/1if_tLrEtxBh1j1ID1OFiEkkLVuvPbgPM7OwZOl8ydtk/edit?usp=sharing

**Comment by WorldImpex** [comment] 2021-12-23 15:05
@natalia-muzyka 
1. Yes I agree
2. The error should be reflected based on E1

![image.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/d88eb85c-e169-4351-8dac-cee1a5db614e)

**Comment by jj105** [comment] 2021-12-28 10:20
I had discussion with @WorldImpex,
for question 2), I think we don't need to export in the csv if user starts from wrong point for now

and about this comment, 
![image.png](https://images.zenhubusercontent.com/5e565f9bd9593e11ebab005a/9a1c3fc6-52c3-4cd0-8318-7945aa53f4b6)

although you didn’t try to draw from 4 to 5 intentionally, I think you put her finger on the screen few more milliseconds after reaching to point 4 and it was interpreted as path from 4 to 5

**Comment by WorldImpex** [comment] 2021-12-29 16:00
- Update activity version 2 name to "Trails_iPad"
- Update activity version 1 name to "Trails_At_Home"
- Change Please take a pen to "You will take a pen"
- Change instructions to each pause there is a next button 
- Turn the first letter green from to black when the user starts 
- Drop the radius of each circle on  test A & B by 5% and copy that to sample A & B. The x,y is correct but the circle should be a bit smaller 
- How long is the delay between the error and the next screen touch? 
   - Show the X, green circle and line disappear at the same time. The green circle, X and the screen disappears then allow the user to draw new line 
-

**Comment by WorldImpex** [comment] 2022-01-10 13:44
Instructions are still in video mode and when a mistake is made, all points are erased. @Matchdev120 has a video

**Comment by natalia-muzyka** [comment] 2022-01-11 09:23
@WorldImpex @Matchdev120 
1. Could anyone help me, please, if I miss something: 
it is expected that assets are updated? Currently, there are equal assets for iPad and Mobile versions and they do not match ZIP assets from requirements(that were implemented and released for iPad version):
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/b24ff7d5-d505-483c-b0fb-5089d31540b8)
2. Headers(Sample A, Test A etc) shouldn't be deleted in this version?

---

- Fixed - Update activity version 2 name to "Trails_iPad"
- Fixed - Update activity version 1 name to "Trails_Mobile"
- Fixed - Change Please take a pen to "You will take a pen" in all instructions
- Fixed - Change instructions to each pause there is in video instructions to a next button so the user can scroll through each step
- Turn the first number/ letter green from the start to black when the user starts. Question: "should the number ""1"" turn black before user starts(when screen is opened) or after user starts?
actual: it is black from the very beginning: https://www.screencast.com/t/BDs2rNszxn
- How long is the delay between the error and the next screen touch? Show the X, green circle and line disappear at the same time. The green circle, X and the screen disappears then allow the user to draw a new line right away.
Actual: incorrect line disappears first. The last correct point stays green and "X" stays on screen until user continues drawing: https://www.screencast.com/t/pVZwJqO2G
- Don't completely understand how can I check this one: Investigate why data export is under 100 in coordinates but the X,Y locations are over 100 for center of dots

**Comment by natalia-muzyka** [comment] 2022-01-13 16:31
Fixed - Assets for iPad match the design (ZIP from requirements)
Fixed - Headers are removed
Fixed - The green circle, X and the screen appear and disappear at the same time

@WorldImpex @Matchdev120 
Question: I'm not sure do these coordinates match the requirement "Investigate why data export is under 100 in coordinates but the X,Y locations are over 100 for center of dots". Screenshot:
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/35af7645-2793-4fe8-acf5-b1e639d4d5d1)

Latest Report files + video:
https://drive.google.com/drive/folders/106hbpEWiObGED0aGfBzLCkWTNIXN5cBO?usp=sharing
https://www.screencast.com/t/L18mwcqNL

Previous report files(Wil confirmed that coordinates are fixed here): https://drive.google.com/drive/u/0/folders/194QBWR2EsoGPxbFGak8_kRcPVmANR4ho

**Comment by natalia-muzyka** [comment] 2022-01-18 09:37
@Matchdev120 @WorldImpex 
Responses aren't saved and submitted after completing the A/B trails applet (checked with newly uploaded applet).
After completing A/B trails activity I can't see responses for regular activities as well. When I log out I see warning about uploading data.
Account: 
josephine_ml@protonmail.com	qwertyui
applet: A/B trails
completing a/b trails: https://www.screencast.com/t/txto4quLLGr1
completing regular activity video: https://www.screencast.com/t/ArSzWnkLZFR

Tried to upload A/B trails protocol on other account, but applet is not appeared after submitting a protocol.
Tried to refresh one of existing a/b trails applets - it  sin't refreshed.
Account:
bernard_ml@protonmail.com	qwe123!!!
create new applet: https://www.screencast.com/t/gQtXZWg9iZl
refresh old applet: https://www.screencast.com/t/mhxir6XiF

**Comment by natalia-muzyka** [comment] 2022-01-18 11:40
the issue from the previous comment is not reproduced anymore.

@WorldImpex @Matchdev120 
how can I compare these coordinates with export?
what I see now:
when there is E0 path let's say 1 ~ 2.
the very first coordinates of this path are almost equal to trail 1 / item 1 coordinates that you shared:

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/171177a0-30c0-417b-ba6d-93b4819fa176)

**Comment by natalia-muzyka** [comment] 2022-01-18 12:45
Coordinates are fixed:

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/81153b04-ac1f-4b82-bd22-0cf00e4e0cc7)

Environment:
ML v0.18.37 staging
iPad Pro (10,5-inch) MQDX2 // iOS 15
https://admin-staging.mindlogger.org/

**Closed** 2022-01-18 16:31 UTC
Labels: CMI Milestone 11.5
