### ISSUE TITLE
Timer: Does not work 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#1690] opened 2021-04-02 15:06 UTC
Steps to recreate
1. Log into admin-staging 
2. Create an schedule for an activity with a timer feature, setting the timer for 1 minute
3. Refresh device and begin activity but do not complete it 
4. Wait over 1 minute 
5. See results

Expected: User sees a count down and the after 1 minute since starting the activity it is completed and saved 
Actual: No count down timer and nothing happens after 1 minute 

![File (1).jpg](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/dd42444d-3fe2-4728-aa90-7aa2dbefdf2e)

**Comment by sergeysemenuta** [comment] 2021-04-07 10:12
The issue is fixed on:
Staging
ML v 0.16.4
iPhone X // iOS 13.3
Pixel 4XL//Android 11
https://www.screencast.com/t/Rf7y6ZbdjUa

**Closed** 2021-04-07 10:16 UTC
Labels: April1, bug
