### ISSUE TITLE
Slider Bar on NIMH should be Discrete 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#862] opened 2020-03-25 14:14 UTC
Steps to Recreate: 

1. Open NIMH applet
2. Select an activity 
3. Find a slider question 
4. View results

Expected Outcome: Slider bar is discrete for the sliders within NIMH 
Actual Outcome: Slider bar is smooth

**Comment by WorldImpex** [comment] 2020-03-31 11:12
![slider.gif](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/c78ee873-d25e-4eb5-94c0-6c6b21a7e541)

Fixed

**Comment by WorldImpex** [comment] 2020-04-01 16:06
Slider is discrete in NIMH now

![File (4).jpg](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/7c0a2963-df20-4bae-87e3-31ed7e6d40e4)

**Comment by sergeysemenuta** [comment] 2020-04-08 13:28
The issue is fixed.
Verified on:
NIMH applet
Prod server
iPhone 7 // iOS 11.4.1 //  v 0.11.21   
Huawei P20 // Android 8.1.0 // v 0.11.21  
iPhone 5s // iOS 12.3.1// v 0.11.21
https://www.dropbox.com/s/qz5gwqzsrljjufb/IMG_1907.MP4?dl=0

Closing the ticket.

**Closed by sergeysemenuta** 2020-04-08 13:28 UTC
Labels: bug
