### ISSUE TITLE
French version: wrong text when taking a photo or video

### ISSUE THREAD

**Issue by lioneldeveauxcri** [ChildMindInstitute/mindlogger-app#1975] opened 2021-09-27 08:44 UTC
The pop-up that appears when you have to choose between using the camera and choosing a video/photo from the device is wrong:
"veuillez saisir du texte" -> "choisir dans la bibliothèque"

**Comment by natalia-muzyka** [comment] 2021-12-03 13:13
@binaryExDev 
there is still not translated to French text: in the confirmation pop-up and after choosing photo/video camera
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/1a7d2f15-a993-4026-a2b6-f42c9f8eb202)

Pop-up is not translated on iOS and Android. Cancel, Retake, Use video/photo buttons aren't translated only on iOS (after choosing photo/video camera)

ML v0.18.8 (staging)
iPhone SE 2020 // iOS 14.2
Samsung S7 // Android 8

**Comment by binaryExDev** [comment] 2021-12-06 02:09
@natalia-muzyka Cancel/Retake/Use Video/Use Photo can't be translated in Mindlogger because the texts are provided by the Operating System. Users can update the texts by changing the primary language of their phones.

**Comment by natalia-muzyka** [comment] 2021-12-06 09:08
Text in the confirmation pop-up and after choosing photo/video camera is fixed.
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/ec8febe4-aa1e-44b0-b540-65795dc7ddb4)

**Cancel/Retake/Use Video/Use Photo buttons are still not translated, though French is a primary system language:**
Video: https://www.screencast.com/t/duWofHbjbZ
ML v0.18.9 (staging)
iPhone SE 2020 // iOS 14.2
Not reproducible on Samsung S7 // Android 8

**Comment by lioneldeveauxcri** [comment] 2021-12-07 09:00
Is the text in the pop-up from my translation file? It's not very idiomatic.

**Comment by natalia-muzyka** [comment] 2021-12-08 14:48
@lioneldeveauxcri could you provide the correct translation, please? it is missing in the Translations/ Localizations file.

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/01f529ad-9942-4ae0-abb4-7a1debb7c6b1)

**Comment by lioneldeveauxcri** [comment] 2021-12-08 15:13
Yes, I couldn't translate properly without the context (because of noun gender)
So:
"Take a new picture or choose one from your library" -> "Prenez un nouvelle photo, ou choisissez-en une dans votre bibliothèque"
"Take a new video or choose one from your library" -> "Prenez un nouvelle vidéo, ou choisissez-en une dans votre bibliothèque"
"Camera" -> "Appareil photo"
"Library" -> "Bibliothèque"

**Comment by binaryExDev** [comment] 2021-12-08 15:21
Sure

**Comment by lioneldeveauxcri** [comment] 2021-12-14 14:36
I'm really sorry, I made a typo in my translation
It's "Prenez **une** nouvelle photo"; "Prenez **une** nouvelle vidéo". I edited my comment accordingly.

**Comment by natalia-muzyka** [comment] 2021-12-14 14:58
@binaryExDev could you change 'un" to "une" in both pop-ups as per the comment above? thank you
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/908ba249-b7e3-40b4-86a3-a00c448b196b)

**Comment by natalia-muzyka** [comment] 2021-12-17 15:52
Verified as fixed on ML v0.18.19 staging
iPhone  8Plus // iOS 13.3
Pixel 3XL // Android 10
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/207bd9f7-1779-4752-b0cb-94d39df7d0df)

**Closed by natalia-muzyka** 2021-12-17 15:52 UTC
Labels: CMI Milestone 10
