### ISSUE TITLE
Discovery: Original Flanker 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#1777] opened 2021-05-20 10:54 UTC
Investigate the feasibility of reconstructing the original Flanker activity and provide an estimate of how long it would take to make it functional again 

[Requirements for new Flanker](https://docs.google.com/document/d/1hxGl3-7gXEP0PaIhGeljJAPTKxCXTOCb5mD4ivgGxEc/edit)

Additional Requirements: 
1. Leave the response options visible during the whole task. Make the buttons unclickable until the stimulus is shown (this only does not allow the user to click the button. The UI of the button should not change) 
2. Implement a short (30 trial) practice session w/feedback. Feedback only on initial practice trials. In production, the practice will be a distinct epoch from the actual task.
3. Reduce the ITI to 1.5s. After Ss press the button (or trial times out), wait 500ms to present the next trial. Current ITI is around 3.7s which feels like forever.
4. Response timeout has to be shortened to 3s.

Please make the export[ look like this](https://docs.google.com/spreadsheets/d/1j7Q_sKBN87QZJid72j8rsBQdcAQgxj59yALTfA4V_W0/edit?usp=sharing)

**Comment by WorldImpex** [comment] 2021-06-21 13:36
https://raw.githubusercontent.com/mtg137/Flanker_applet/master/protocols/flanker/flanker_schema

**Comment by natalia-muzyka** [comment] 2021-11-30 12:18
1. I don't have access to this [doc](https://docs.google.com/presentation/u/0/d/1loyTHS0cXFoCjFXRM62wcVHD40mx7v_0iPaZIkBKzXE/edit), requested an access
2. as per Question #4 in the [doc](https://docs.google.com/document/d/1hxGl3-7gXEP0PaIhGeljJAPTKxCXTOCb5mD4ivgGxEc/edit) were there created different sets with different order of questions to test? or the schema from the comment above is the one to test? https://raw.githubusercontent.com/mtg137/Flanker_applet/master/protocols/flanker/flanker_schema
3. the practice session should contain 20 trials with feedback as in the task or 30 as in the doc? actual behavior: there are 30 trials with feedback
4. what is the ITI time?
5. '"In production, the practice will be a distinct epoch from the actual task." - does it mean that demo (initial practice trials with feedback) will be implemented as a separate activity in the applet?
6. what is the required report displaying? above or below in the [doc](https://docs.google.com/spreadsheets/d/1j7Q_sKBN87QZJid72j8rsBQdcAQgxj59yALTfA4V_W0/edit#gid=710500285)? current displaying is totally different: 
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/ec9f787c-52a9-4e4b-83cb-aac17400c8e5)

**Comment by mtg137** [comment] 2021-12-02 17:55
@natalia-muzyka 
1 - I don't have access to that doc too, I used only [this doc](https://docs.google.com/document/d/1hxGl3-7gXEP0PaIhGeljJAPTKxCXTOCb5mD4ivgGxEc/edit) when I was building flanker task and I think it includes everything
2 - schema from comment above is the one to test
the randomization of question is implemented on mobile app side, so if you start activity one time then we'll see questions in one order, and if you start next time then we'll see questions in different order
3 - I think 30 trials with the feedback is correct
4 - I think it means fixation time and 1.5 second is old requirement
![image.png](https://images.zenhubusercontent.com/5fbce3e9259bafeab239c8c3/ab5b6b98-9a11-4dd7-bda2-cef095afe8cc)
5 - yes I think so, I was thinking we need to refactor schema a bit when we release it to production
6 - could you double-check it when you get chance? I think my PR for admin panel was not deployed when you were checking.

**Comment by WorldImpex** [comment] 2021-12-03 13:07
@mtg137 It is 30 per Stan's reply 
![image.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/51cc3d65-29bb-49b0-9ea1-8ddec21fb369)

**Comment by natalia-muzyka** [comment] 2021-12-09 12:08
@WorldImpex @mtg137 

**1. each test session contains 360 trials instead of 120**
ZIP: [https://app.zenhub.com/files/103405139/83bc9bae-c777-4408-ae75-e8055e45e51a/download](https://app.zenhub.com/files/103405139/83bc9bae-c777-4408-ae75-e8055e45e51a/download)

---

**2. because of issue #1 the Total screen with greyed "Finish" button is displayed after each test block within the MAIN test**
video: https://www.screencast.com/t/1UqalcmlS

---

**3. the "back" and "skip" buttons are always available and clickable, user can move back to the task from the Total screen or skip the entire activity**
video:  https://www.screencast.com/t/lxuR9eMV

---

**4. response expected is incorrect in CSV report (event type, accuracy, response value matches):**
video of taking the first six trials: https://www.screencast.com/t/edgJoSQIGE
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/7da1229d-fec6-42c3-adb2-03da2a236207)

---

**5. shouldn't clock stamps be displayed as the timestamps in general exported CSV file (date, time with milliseconds)?**
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/b4fd05fb-3e5e-4b09-885d-bb7254728342)

---

**QUESTIONS:**

**1. Expected display onset for fixation screen starts from 0 in each report**, in the report example it starts from positive value(1500). I assume that is correct to start from 0 'cause this is the very beginning of activity? I think I need more clarification about onset/offset values. 
How I understand it, (please, correct me if I'm wrong): 
*Time of starting activity is 0. 
*Expected Onset - the desired time when the screen should be opened.  
*Actual onset - when the screen was actually opened.
*Expected offset - when the current screen should be changed by the next screen (expected onset + fixation time or maximum response time)
*Actual offset - when user selected response or when max response time is up (without any action from user), or when the fixation screen time is up
*Response time = Actual offset - Actual onset
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/04cd2687-8fdf-4026-a143-8478a222ce8b)

---

**I assume that is acceptable for current implementation but want to clarify:**

**2. The naming of event(stimulus) types should match the example?** -1 is equal to fixation, but the rest types don't match. I assume that naming is flexible and acceptable?
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/27c5e44e-d728-4322-86e9-c597aa709f50)

**3. the "finish" button is displayed on the practice total screen after achieving 75% accuracy** (expected to see "continue" or "ok", so the "finish" should be on the last screen before the "thanks" screen"). info text press the button below to continue, it is a little bit confusing.
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/6130765d-7966-4261-b1c1-2534d0009b95)video: 

**4. fixation screen contains the "+" instead of "-----"**

Environment:
ML v0.18.12 (staging)
iPhone 12 Pro Max // iOS 15.0.1
account owner: bernard_ml@protonmail.com / qwe123!!!
account user: kimberly_ml@protonmail.com	/ 12345678 (secret id: iPhone 12 pro max)
applet: flanker (1)

**Comment by natalia-muzyka** [comment] 2021-12-09 15:38
one more question:
resuming the activity isn't implemented in the current iteration?
https://www.screencast.com/t/t7pELkLhmb

**Comment by mtg137** [comment] 2021-12-09 15:49
I think in current version, resuming activity will redirect user to starting point of phase that user was on.

if user was on second test phase before closing activity, he will preserve his responses for first test phase and trial phase

**Comment by mtg137** [comment] 2021-12-10 07:08
for comment 5, I think we need to display timestamps in integer format for flanker task

For question 1, I think it's correct to start from 0
For question 2, in the [example data export](https://docs.google.com/spreadsheets/d/1j7Q_sKBN87QZJid72j8rsBQdcAQgxj59yALTfA4V_W0/edit#gid=710500285), I think left-neutral and right-neutral event types are not considered in "Stimulus Type" column

![image.png](https://images.zenhubusercontent.com/5fbce3e9259bafeab239c8c3/f75eb3a7-03da-4ea6-9a99-95f41a4d007c)

**Comment by mtg137** [comment] 2021-12-10 07:10
This is description about columns that we received when we were working on building flanker task.

Expected Display Onset: int time in ms representing the pre-computed time at which the stimulus should appear, relative to the start of the task. 
Actual Display Onset: in time in ms representing the time at which the stimuli were actually delivered. Given the lack of a video blank/refresh marker, This will be the time at which the call to display the stimulus returns/'completes'. - relative to the start of the task. 
Display Duration: int time in ms representing the time that the stimuli should remain on the display screen. However, the flanker stimuli will be removed at the time of the Ss' response, and may not be relevant here but should be reported for consistency across RT-based cognitive tasks. I'd suggest that for self-paced tasks that this represents the max duration value. 
Expected Display Offset: int time in ms representing the pre-computed time at which the stimulus should be removed from the screen. i.e. expected display onset + Display Duration - relative to the start of the task. 
Actual Display Offset: int time in ms representing the time at which the stimuli were actually removed from the screen. Given the lack of a video blank/refresh marker, This will be the time at which the call to remove the stimulus from the screen returns/'completes'. - relative to the start of the task. 
Expected Display Onset(Clockstamp): [ I changed from offset to onset] int time in ms representing the pre-computed time at which the stimulus should appear - in system time.
Actual Display Onset(Clockstamp): [ I changed from offset to onset]  int time in ms representing the pre-computed time at which the stimulus should be removed - in system time.
Trial Clockstamp:  int time in ms representing the start of each individual trial in system time.
Experiment Clockstamp: int time in ms representing the start of the experiment - in system time. This is the T0 used to compute all of the relative timing measures.

**Comment by natalia-muzyka** [comment] 2021-12-10 08:45
@mtg137 thank you for the additional info!
I have a few more **questions**:

**5. that is correct that response and fixation have the same stimulus type value?**
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/2c5d7901-fe63-4db0-8efc-05e5f96a00e8)

---

**6. as per the comment above Display Duration is defined as "the time that the stimuli *should* remain on the display screen". Currently, it shows the actual time of remaining the stimuli on the screen: Actual offset(when user responded) - Actual onset(when screen was opened).**  I expected to see here the next values:
for response = 3000ms, for fixation and feedback 500ms. Please, correct me if I'm missing something.

---

**7. There are two similar values in the report: Actual Display Offset and Response time column**
The response time column is missing in your comment, so I want to clarify: 
I understand that the Response time should be calculated as the Actual offset - Actual onset.
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/483e1df1-04c0-4669-a7ce-28dd06d5f94c)

---

**8. for calculating the Expected Display Offset there are used fixed expected Display duration values, right? for response = 3000ms, for fixation and feedback 500ms**

---

**9. if we need to have clockstamps in this format, could you help me, please, how can I check that they are correct?** and I'm sorry, it is not enough clear for me what do you mean saying [ I changed from offset to onset]?

**Comment by mtg137** [comment] 2021-12-10 09:04
5. @WorldImpex - could you please let us know expected behavior?
6. yes, you are correct, I'll fix it
7. yes I think their values are same ( since they are in different rows I thought data might be processed in different aspects )
@WorldImpex - could you please confirm it?
8. yes
9. in previous version of export document, the name of column was **Actual Display Offset(Clockstamp)**
it is now updated to **Actual Display Onset(Clockstamp)** in google doc

I think you can use [this](https://timestamp.online/) to check timestamp values?

**Comment by WorldImpex** [comment] 2021-12-10 14:19
@mtg137 Please also update the below 
1. In the test instructions we say "Practice instructions" Please just show Instructions 
2. Replace the words Trail with Block 
3. The stimulus for some combinations is overlapped on an iPhone 13 pro. Please fix

**Comment by WorldImpex** [comment] 2021-12-13 10:02
@mtg137 
2.  I'm not sure why left-neutral and right-neutral event types would not be considered in Stimulus Types. They are clearly types of stimuli. A "-1" should represent fixation events, and 1-6 for each of the six stimulus types that you present. As for the numbering, It would be best if we could split L/R as odd and even, and arrange the stimulus types in ascending complexity, so: 1=left_neut, 2=right_neut, 3=left_con, 4=right_con, 5=left_inc, 6=right_inc. Should probably also add the 'u' to neut, so that folks aren't confused about a 'net' stimulus.

5. The stimulus type and response for each trial should match one another.. E.g. if a trial displays a right_con stimulus to the user, this should also be noted in the corresponding response. Otherwise, it will be unnecessarily difficult to know what stimulus type the response belongs to. 

9. It looks like you are using "display offset" as a proxy for the timing of the button press? If so, you should be using the timestamp for the button press. The column "Response Time" should be the timestamp from when the user responds minus the stimulus onset timestamp. While we do care about the timing of the stimulus offset, the primary thing of interest in a response time is the time that the user responds, relative to the time that the stimulus of interest appears on the screen. There's no point in adding in potential variance between the time that the button is pressed and when stimuli go off of the screen.

**Comment by natalia-muzyka** [comment] 2021-12-13 15:54
My comment:

**#1 & #2 fixed** 
each test session contains 360 trials instead of 120
Total screen with greyed "Finish" button is displayed after each test block within the MAIN test
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/3a6de930-3a6e-40c9-8f15-267891898c41)

**#3 fixed:** Skip and Back buttons are removed from practice and test screen
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/23f201e0-9b10-418c-ac08-65782b8c1434)

**#4 is NOT FIXED,** 
Expected response is still incorrect in CSV:
https://www.screencast.com/t/HrhfM9VsD
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/47ab7ced-2745-44ca-afaa-9968478b0bb0)

**#Q3 fixed** - the "finish" button is displayed on the practice total screen after achieving <75% accuracy
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/8b1478fa-9517-452d-8acd-13d6832507b2)

**#Q4 fixed** - fixation screen contains the "+" instead of "-----"
https://www.screencast.com/t/O6hpwWMmMd9

**#6 is NOT FIXED** need to confirm
Display Duration is defined as "the time that the stimuli should remain on the display screen". Currently, it shows the actual time of remaining the stimuli on the screen: Actual offset(when user responded) - Actual onset(when screen was opened). 

---

**From Wil's comment:**

**Not fixed:**
#1 Practice instructions is still displayed on the break screens (between 1, 2 & 3 blocks)
https://www.screencast.com/t/i5yLioHXeTd

#2 Word "trails" is not replaced on summary screens:
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/501780dc-8e88-41ef-9e49-7eaa4573a337)

#3 @WorldImpex unfortunately, we have no such device to check the reproducibilty

**Comment by natalia-muzyka** [comment] 2021-12-13 16:32
[UI] OK and Continue button looks too big on small screen devices:
iPhone 6S // iOS 14.4.2 // 4.7
Samsung S7 // Android 8 // 5.1
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/2f562406-d0ae-41ef-918f-5daaa8e2b558)

[iPhone 6S / iOS 14.4.2] There is a few seconds delay after opening the test screen:
https://www.screencast.com/t/fUFcuZ5oZ

**Comment by mtg137** [comment] 2021-12-13 17:59
@natalia-muzyka - for timestamp comment, I think there's difference because of timezone

in the data export, we use UTC timezone for activity start and activity end times
however in the [online converter](timestamp.online), they show date times in the user's browser's timezone

if we convert 12/13/2021 6:58:34 PM GMT+2 to utc time, it will be 12/13/2021 16:58:34 which is same as exported data

**Comment by mtg137** [comment] 2021-12-13 18:04
@WorldImpex - I think we have delay in some devices because it takes some time to preload some assets for the flanker task

can we show activity indicator while assets are loaded?

**Comment by WorldImpex** [comment] 2021-12-13 18:54
Yes that works @mtg137

**Comment by natalia-muzyka** [comment] 2021-12-14 10:34
@mtg137 @WorldImpex could anyone clarify, please, what was changed in the export? I\m trying to compare Wil's latest comment but don't see any changes accordingly to it. Please, let me know what should I retest in the export.
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/3eb7fc62-82c6-4d32-a431-88989e7920bd)


**Not fixed issues:**

**_Wil's comment:_**
1. The "Practice instructions" is still displayed on the break screens instead of "Instructions" (between 1, 2 & 3 test blocks):
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/e8eac9d5-44dd-4cb4-a26b-32ef15df0633)

2. @WorldImpex  I need to clarify: only the word "trial" should be replaced? In the meaning: there are blocks, that contain trials. So when Total screen says "You responded correctly on X% of ... " there should be word "trials", but in the last sentence "press the button below to end current ..." there should be "block"? 
Word trial is not replaced on the 
- total screens (press the button below to end current trial)
- break screens (between 1, 2 & 3 test blocks)
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/a9c5b839-f8ff-4728-80c5-bb34bed79c8b)

_**My comment:**_
There is a few seconds delay after opening the test screen/instruction screen/completing the activity and loader isn't shown:
https://www.screencast.com/t/lKSE3OQ0q
iPhone 6S / iOS 14.4.2
Samsung S7 // Android 8

---

**Fixed:**
[UI] OK and Continue button looks too big on small screen devices and tablets
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/d0389131-c0e5-492a-b3ba-224f01b562b8)

---

**New:**

**User has the ability to move Back from instructions screen to test block with "Back" button.** As I understand there should be the ability only to move forward.
video: https://www.screencast.com/t/tl5EEze5G5Cv
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/f0d9bed2-0094-452f-9d64-4b003a7d47b2)


**If user didn't achieve 75% score at the third time the screen with "restart the trial" instruction is displayed**. Expected to see "press the button below to continue" (as for the
https://www.screencast.com/t/rN3s3vNAXpMP


**When user finishes the activity the last screen says "press below to continue"**
https://www.screencast.com/t/oQ8ZgaknUbq


**Average response time is NaNms if user selected all the incorrect responses**
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/a346560a-4215-4bb9-99ec-16d713a94674)


**iPad Air 2 / iOS 14.6 Activity crashes on the first practice block**
https://www.screencast.com/t/1Szya36j

**If user closed activity on the Total practice screen after resuming the practice block will be restarted.**
Even if user achieved 75% score, the practice block will be restarted.
https://www.screencast.com/t/dWBkfENrDhX3

---

Checked on ML v0.18.15 (staging)

**Comment by WorldImpex** [comment] 2021-12-14 13:10
2. Yes it makes sense to leave these as trails

**Comment by natalia-muzyka** [comment] 2021-12-14 13:33
ok, in this case, @mtg137 , please, change 
1. the blocks back to trials:
-on the general instructions
-on the total screens (you responded correctly ...)
2. trial to block
-on the total screens last sentence (press the button below to end current...)
-on the practice instructions screen (press the next button to start next...)
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/9d285801-a629-4737-a940-5479e93f5ebc)

**Comment by mtg137** [comment] 2021-12-14 18:11
for the data export, I think [my PR](https://github.com/ChildMindInstitute/mindlogger-admin/pull/1371/commits/d06923fcf4f865dc23f745ae2146e8143fa7f4a7) on admin panel is not deployed

stimulus type and response time are fixed on the PR, I'll discuss with Ben to deploy PR

**Comment by mtg137** [comment] 2021-12-14 20:15
I discussed with @WorldImpex about the problem with closing and resuming activity

I think we are ok to restart trial after resuming activity

**Comment by natalia-muzyka** [comment] 2021-12-15 08:52
@mtg137 @WorldImpex 
I refreshed Flanker, started it on iPhone(ML v0.18.16 staging) and see:
1. there are only 6 trials per practice block,
2. 12 trials per test block,
3. infinity loader after tapping the "ok"/"continue"/"finish" button on total screen (can be fixed with tapping the Next/Done).
Video: https://images.zenhubusercontent.com/103405139/7c34e305-0e84-46cf-a5a2-fbdb04ed0da9/flanker.mp4

**Comment by natalia-muzyka** [comment] 2021-12-16 16:04
@mtg137 @WorldImpex 
- [UX] User can accidentally close the Total screen when taps the stimuli on the last screen:
https://www.screencast.com/t/KgHSVcRXg2Wq

- Null value in CSV report if user didn't answer (Respond faster message)
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/3862ea4c-9311-4a3c-8cf8-12469f341141)

- I assume this is correct behavior, just want to be sure: If app goes to the background, the activity is paused. After the app was recalled, activity is continued. Data are saved to report. Actual display offset will be shifted to the time, that app was in background:
![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/41254745-fe17-4c26-85ec-f039b72cfd3c)

---

**Fixed:**
1. the "finish" button is displayed on the practice total screen after achieving 75% accuracy (expected to see "continue" or "ok", so the "finish" should be on the last screen before the "thanks" screen"). info text press the button below to continue, it is a little bit confusing.
2. In the test instructions we say "Practice instructions" Please just show Instructions
3. Replace the words Trail with Block
4. The naming of event(stimulus) types
5. The is a few seconds delay after opening the practice/test screen
6. User has the ability to move Back from instructions screen to test block with "Back" button. As I understand there should be the ability only to move forward.
7. When user finishes the activity the last screen says "press below to continue"
8. Average response time is NaNms if user selected all the incorrect responses
9. infinity loader after tapping the "ok"/"continue"/"finish" button on total screen (can be fixed with tapping the Next/Done).
10. Incorrect quantity of trials (6 per practice block, 12 per test block)
11. Response time value
11. Display duration value

**Comment by natalia-muzyka** [comment] 2021-12-21 09:04
Background behavior was confirmed as acceptable.
The rest three issues have separate reports now and are backlogged:

https://app.zenhub.com/workspaces/mindlogger-webapp-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-app/2187
https://app.zenhub.com/workspaces/mindlogger-webapp-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-admin/1385
https://app.zenhub.com/workspaces/mindlogger-webapp-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-admin/1386

**Closed by natalia-muzyka** 2021-12-21 09:04 UTC
Labels: CMI Milestone 10
