### ISSUE TITLE
[Redesign]Expanding all activities is not working

### ISSUE THREAD

**Issue by Matchdev120** [ChildMindInstitute/mindlogger-app#1435] opened 2020-12-30 21:46 UTC
**Steps to reproduce:**
1. Log in to the admin panel https://admin-new.mindlogger.org/ (mrn@ml.com // 123456)
2. Select NIMH applet and view chart for an user
3. Click on expand all button in response tab.

**Actual result**: Some items don’t have graphs associated with it after expanding all activities.
**Expected result**: Expanding all should work fine.
(**Note**: This issue happens on only huge applets like NIMH EMA Applet)

**Comment by sergeysemenuta** [comment] 2021-01-04 16:08
The issue is fixed on https://admin-staging.mindlogger.org/
Checked the MIMH applet
https://www.screencast.com/t/7UkiIOwzMy

**Closed by sergeysemenuta** 2021-01-04 16:08 UTC
Labels: adminpanel, bug
