### ISSUE TITLE
Bold Subscale Text in Summary Screen for Flagged Scores

### ISSUE THREAD

**Issue by e-kass** [ChildMindInstitute/mindlogger-app#2867] opened 2022-09-01 21:27 UTC
Any subscale that is flagged should have **bolded** text in addition to bolded numbers

Bennett requests this.

![Screen Shot 2022-09-01 at 5.25.04 PM.png](https://images.zenhubusercontent.com/6310fa4035485166fdf9897e/7b15171d-50e9-4a0b-9b88-a6207238cf7e)

**Comment by anq83** [comment] 2022-09-15 09:21
I've fixed it for mobile apps.
In the PR: 
https://github.com/ChildMindInstitute/mindlogger-app/pull/2870

But it also should be fixed in PDF reports generation.

**Comment by anq83** [comment] 2022-09-15 09:24
Also discovered, that on iOS (iPhone11) icons missed.
Please add a new bug or review if the one already exist.
@yzenchanka 
@natalia-muzyka 

![image.png](https://images.zenhubusercontent.com/6316373a3fb7f6df366b544d/6b442467-2f50-4a21-a939-44b6423d2c91)

![image.png](https://images.zenhubusercontent.com/6316373a3fb7f6df366b544d/b63f659a-afe4-470f-8750-b46bc8a456c3)

**Comment by anq83** [comment] 2022-09-15 09:28
Assigned to @Tom1204

**Comment by natalia-muzyka** [comment] 2022-09-15 12:01
@anq83 I can't reproduce the missing icons issue on my iOS devices. Could you share your iOS version, please?
@yzenchanka could you try to reproduce this bug on your devices, please?

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/4d290169-85f3-4abb-a1c8-f79277a91983)

Environment:
ML Pilot v0.21.48 staging
Apple iPad 9th gen (2021) / iOS 15.5
iPhone 7 // iOS 13.1.1
user-stg@ml.com	/ 123456
Config reports v9 / Test A (1)

**Comment by yzenchanka** [comment] 2022-09-16 08:43
I also can't reproduce the missing icons issue on my iOS devices:
Environment:
ML Pilot v0.21.48 staging and v0.21.51 staging
Apple iPad 7th gen (2021) / iOS 15.4.1
iPhone 7+ DM // iOS 14.4.1
[juliayzenchenko+1@gmal.com](mailto:juliayzenchenko+1@gmal.com) // Ngromyko889)
Test Applet 2 / Test A_1
![image](https://user-images.githubusercontent.com/112855442/190596239-7916d9b8-0258-40ab-b9d2-bc263d841725.png)

**Comment by natalia-muzyka** [comment] 2022-09-16 10:30
Verified as fixed on iOS:

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/39111b91-812d-4981-bfcf-082d918cb069)

Environment:
ML v.0.21.52 staging
iPhone 7 // iOS 13.1.1
Apple iPad 9th gen (2021) / iOS 15.5

**Comment by anq83** [comment] 2022-09-23 07:47
I've observed it on simulator iPhone 11.
So, if we cannot to reproduce then let's close it.
Anways if you find issing icons later - the new ticket should be.

**Comment by yzenchanka** [comment] 2022-09-23 08:02
Verified as fixed on Android:
![image](https://user-images.githubusercontent.com/112855442/191916753-74310220-b592-4e1a-b842-5cced72a4c18.png)

Environment:
ML v.0.21.52 staging
Samsung Galaxy S20 FE SM-G780G // Android 12
Google Pixel XL // Android v10

**Comment by natalia-muzyka** [comment] 2022-10-24 14:00
@Tom1204 the issue should be fixed on PDF report side as well:

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/63d20e91-788a-45cc-9840-0c81854a87ae)

https://admin-staging.mindlogger.org/
Win 10 / Chrome 103
test_account@ml.com / 123456
Config report with flag
Applet password:	Qwe123!!!

cc: @eleonova-scn

**Closed** 2022-11-15 08:33 UTC
Labels: Config Report, EK-High Priority
