### ISSUE TITLE
Positions on Slider do not Match the Options

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#667] opened 2020-01-15 18:32 UTC
Expected Result: Depending on what the JSON scale is, the display would mirror
Actual Results: The value of the position of the movable slider is incorrect. It should be 0 to 5 and not 1 to 6

**Comment by shnizzedy** [comment] 2020-01-15 18:44
Duplicate of https://github.com/ChildMindInstitute/mindlogger-app/issues/289

**Closed** 2020-01-15 18:48 UTC
Labels: bug
