### ISSUE TITLE
New individual Events Do Not Show on Admin Panel

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#917] opened 2020-04-13 19:20 UTC
Steps to recreate
1. Select an applet 
2. Select view users
3. Select a day and setup an event
4. See results

Expected Results: New event is on the calendar and stays on the calendar after the user selects save
Actual Results: The user cannot see the newly created event on the calendar

**Comment by sergeysemenuta** [comment] 2020-04-30 11:41
Unable to close the issue untill the https://app.zenhub.com/workspace/o/childmindinstitute/mindlogger-app/issues/900 is fixed

**Comment by sergeysemenuta** [comment] 2020-05-13 17:35
The issue is not reproduced .
Video: https://www.dropbox.com/s/yko260zwpxel1qt/2020-05-13_20-32-11.MP4?dl=0
Checked on :
Dev server
https://admin.mindlogger.org/
Win 10 x 64 // Chrome

**Closed by sergeysemenuta** 2020-05-13 17:35 UTC
Labels: bug
