### ISSUE TITLE
⏬"See more" button should disappear when user scrolls down to end of screen

### ISSUE THREAD

**Issue by hotavocado** [ChildMindInstitute/mindlogger-app#703] opened 2020-01-23 21:16 UTC
![seeMore](https://user-images.githubusercontent.com/24463939/73024318-56c41c80-3dfb-11ea-8a23-44cfbc471fd6.gif)

The see more button is still there when a user scrolls manually to the end of the screen, have to tap to get rid of it. This might be annoying to the user. Can we get the button to disappear automatically when a user scrolls to the bottom?

**Comment by binarybottle** [comment] 2020-01-23 22:14
How odd -- The button disappears on the Pixel 4XL and iPhone 11 Pro when logged into your account, @hotavocado!

**Comment by hotavocado** [comment] 2020-01-23 22:52
that's good news!

**Comment by WorldImpex** [comment] 2020-01-24 14:57
Duplicate of https://app.zenhub.com/workspaces/mindlogger-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-app/675

**Closed by WorldImpex** 2020-01-24 14:57 UTC
