### ISSUE TITLE
A/B Trails: Error Delay and Erroneous Line 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#2642] opened 2022-06-01 17:17 UTC
Steps to recreate 
1. Open A/B Trails applet and start on an item
2. Draw a line from Start point to Error 
3. See the error and immediately try drawing a new line 
4. See results 

Expected: A new line is drawn while showing the error and the user is successful in either connecting to the correct dots or is shown another error.
Actual: No lines are drawn after multiple attempts and when error disappears a line is shown the user did not draw. 

https://images.zenhubusercontent.com/103405139/108625e3-04e1-4e86-b1e1-7be8c3340dec/pxl_20220601_163141045_ts_2.mp4

**Comment by WorldImpex** [comment] 2022-06-09 12:42
There is still a delay when repeatedly starting from a start point and drawing errors or connecting to the right number

**Comment by WorldImpex** [comment] 2022-06-10 09:41
Ghost lines are still showing up after trying to draw a line with an error present

**Comment by WorldImpex** [comment] 2022-06-13 17:25
I am still seeing a small delay sometimes between error message being shown and the ability to draw another line

**Comment by natalia-muzyka** [comment] 2022-06-14 11:11
@WorldImpex @mtg137 it was decided to remove the X to reduce the delay? If yes, then the issue is fixed.

**Comment by WorldImpex** [comment] 2022-06-14 11:45
@mtg137 Can the X be there and the delay is still removed?

**Comment by mtg137** [comment] 2022-06-14 13:37
yes, the red X can be there and delay is still removed.

**Comment by WorldImpex** [comment] 2022-06-14 13:53
Please add it back @mtg137

**Comment by natalia-muzyka** [comment] 2022-06-17 07:52
@mtg137 red X is still missing.
Checked with newly created a/b trails applet and activity.
Video: https://www.screencast.com/t/p3tR0Zd16h

ML v0.21.9 staging
Samsung Galaxy Tab S6 SM-T865 // Android 9.0
Apple iPad 9th gen (2021) / iOS 15.5
owner: ml3_general_acc@protonmail.com / 12345678
test-user6@mail.com / qwerty
a/b trails (1), cognitive tasks ml3
Applet password:	Qwe123!!!

**Comment by mtg137** [comment] 2022-06-17 07:54
I think my PR for showing red X is not merged yet.
https://github.com/ChildMindInstitute/mindlogger-app/pull/2670

I'll discuss with @devbtech

**Comment by natalia-muzyka** [comment] 2022-06-20 13:55
Verified as fixed: https://www.screencast.com/t/sBakuya8m

ML v0.21.10 staging
iPhone 7 // iOS 13.1.1
Samsung Galaxy S7 // Android 8
Google Pixel 5a // Android 11
Samsung Galaxy Tab S6 SM-T865 // Android  9.0
Apple iPad 9th gen (2021) / iOS 15.5

**Closed by natalia-muzyka** 2022-06-20 13:55 UTC
Labels: bug, CMI Milestone 15
