### ISSUE TITLE
Push Notifications Not Received

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#850] opened 2020-03-22 17:03 UTC
Steps to recreate: 

1. Log onto admin dev environment and select NIMH applet
2. Select an activity that is all day and set a notification for 10 mins into the future
3. See results 

Expected Results: The user receives a notification in 10 mins 
Actual Results: No notification received 

![Screen Shot 2020-03-22 at 12.57.48 PM.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/48f2266d-b575-42d6-8ea5-c32190999204)

**Comment by sergeysemenuta** [comment] 2020-04-02 08:44
The push notifications are not received
Steps to repro:
1.Log onto admin dev environment and select NIMH applet
2. Select several users and click the "Continue" button
3. Set up an individual schedule for those users
Video: https://www.screencast.com/t/ZdygKdkr
4. Wait for receiving the notifications

Actual result: The push notifications are not received for the scheduled time 
Note: Only one user has received duplicated notifications (EMA Assessment (Morning)) with settings applied (Only notify If  activity has not been completed by ....) on the iPhone 5s //iOS 12.3.1
Expected result: All users  should be received push notifications  for the scheduled time

Checked on : 
iPhone 5s // iOS 12.3.1// v0.11.19
iPhone 7 // iOS 11.4.1 //v0.11.19
Huawei P20 // Android 8.1.0 //v0.11.19

**Comment by sergeysemenuta** [comment] 2020-04-08 13:06
The issue is not reproduced anymore.
Users are received all types of notifications.
Verified on:
Prod server
iPhone 7 // iOS 11.4.1 //  v 0.11.21   
Huawei P20 // Android 8.1.0 // v 0.11.21 
 iPhone 5s // iOS 12.3.1// v 0.11.21

Closing the issue.

**Closed by sergeysemenuta** 2020-04-08 13:06 UTC
Labels: bug
