### ISSUE TITLE
Duplicate Draw Downloads

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#2361] opened 2022-01-28 13:48 UTC
1. We have a stakeholder that when downloading the draw data twice, the activity_end_times (as well as filesnames) differ from download to download 
2. Each duplicate has a unique hexadecimal filename, and a new row in the reports.csv file making it appear to be a completely valid new entry. However, if you check filesize and/or run a diff on the files, you can see that they are identical, despite being assigned a new ID/Session hex code combo. 
3. Filename is repeated in a "response" column, but prepended by "file:,", and without the csv extension (e.g. filename: 61cbcca0025fb7a0d64788d9-61b2103c9c4ebd9574b05128-Screen6).

[Data Set](https://drive.google.com/file/d/1SIZQoGmRxw3KzZ0gIyN6f_opKTKJXinF/view?usp=sharing) 
[File Summary](https://drive.google.com/file/d/154JaIA7tE2vxLPDeK_VssbUZUp8N8ekD/view?usp=sharing)

Please investigate and respond to the feedback

**Comment by mtg137** [comment] 2022-02-07 21:08
we can leave 3 in the current status for now ( I discussed with @WorldImpex )

- we didn't display extension in the report file because media files have svg extension and reports have csv
- response is prepended by **file:** because we have optional text input field for drawing item and it is displayed with **text:** prefix

**Comment by natalia-muzyka** [comment] 2022-02-09 09:43
1. Fixed: the activity_end_times (as well as filenames) is the same from download to download: https://www.screencast.com/t/Ts2hXLtsbfE
2. After an investigation @mtg137 defined that duplicated responses were caused by hitting the "Done" button(mobile app) a few times because of the delay on the last screen of activity with a big amount of data. 
Is resolved by adding a delay to the "Thanks" screen and implementing the "Please wait..." info message before showing the "Close" button: https://www.screencast.com/t/hxYojssaqp

Verified as fixed on:
https://admin-staging.mindlogger.org/
ML v0.18.47 staging
Samsung Galaxy S7 Edge SM-G935FD // Android 8
iPhone 8 Plus // iOS 13.3
Samsung Galaxy Tab S6 SM-T865 // Android 9.0
iPhone 7 // iOS 13.1.1
iPad Pro (10,5-inch) MQDX2 // iOS 15
iPhone 6S // iOS 14.4.2

**Closed by natalia-muzyka** 2022-02-09 09:43 UTC
Labels: bug, CMI Milestone 11.5
