### ISSUE TITLE
[Production] The notifications are not fired on the device

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-app#1505] opened 2021-01-19 10:00 UTC
**Steps to reproduce:**
1. Log in to the admin panel https://admin.mindlogger.org/ (prodml@yandex.ua // 123456)
2. Select any applet and schedule events with notifications
3. Log in to the app
4. Wait for the notifications
5. Look at the result

**Actual:** The notifications are not fired on the device
**Expected**: The notifications are fired

**Environment:**
https://admin.mindlogger.org/
ML v 0.14.63
Pixel 4XL//Android 11
iPhone 11 Pro Max // iOS 13.5.1

**Comment by sergeysemenuta** [comment] 2021-01-19 14:40
The issue is fixed
![2021-01-19_16-38-56.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/83dcac6c-b7c7-447a-84d8-2afcdfb352ae)
Verified on:
ML v 0.14.63
Pixel 4XL//Android 11
iPhone 11 Pro Max // iOS 13.5.1

**Comment by sergeysemenuta** [comment] 2021-03-24 09:47
Notifications do not fire in the production accounts
Owner: prodml@yandex.ua // 123456
NIMH, DBT applets. Applet password: Qwe123!!!
Users:
prodml1@yandex.com // 123456
prodml2@yandex.com // 123456

Environment:
https://admin.mindlogger.org/
ML v 0.15.25
Pixel 4XL//Android 11
iPhone X // iOS 13.3

**Comment by sergeysemenuta** [comment] 2021-03-24 14:23
Rechecked  on:
ML v 0.15.25
Pixel 4XL//Android 11
iPhone X // iOS 13.3
Notifications are fired

**Comment by sergeysemenuta** [comment] 2021-05-28 09:22
The issue is reproduced again in Production
ML v 0.16.15 (release version)
Phone X // iOS 13.3

**Comment by natalia-muzyka** [comment] 2021-05-31 14:29
On staging notifications work
The issue is reproduced on production
Owner: prodml@yandex.ua // 123456
NIMH, DBT applets. Applet password: Qwe123!!!
Users:
prodml1@yandex.com // 123456
prodml2@yandex.com // 123456

Environment:
https://admin.mindlogger.org/
ML v 0.16.15
iPhone XR // iOS 14.3

**Comment by natalia-muzyka** [comment] 2021-05-31 15:31
On the production notification looks like a "past due" right after rescheduling on the future time via individual calendar
ML v 0.16.15 (prod)
iPhone XR // iOS 14.3
https://images.zenhubusercontent.com/103405139/6891d339-d4cb-41ad-84bf-4657b574840a/past_due.mp4

**Comment by natalia-muzyka** [comment] 2021-06-01 08:21
still reproduces on production
Owner: prodml@yandex.ua // 123456
NIMH, DBT applets. Applet password: Qwe123!!!
Users:
prodml1@yandex.com // 123456
Environment:
https://admin.mindlogger.org/

noticed that with the same settings on calendar:
- activity start time: always available
- notifications: turn on + future time,
I have differences in events: 
1) on staging I have "availability: true" in request, and on prod I haven't
2) on prod the activity is displayed as "past due" right after scheduling
could the absence of this option have an impact on notifications?
https://www.screencast.com/t/txtX81Vw5Sss

video with all settings for prod request
https://images.zenhubusercontent.com/103405139/e75f5159-4840-4ee4-95d9-b7a63c1928cb/prod_notifications.mp4

**Comment by natalia-muzyka** [comment] 2021-06-15 09:28
**Not reproduced. The notifications are fired on the device in the prod environment.**
https://www.screencast.com/t/Blgb5To2

Owner: prodml@yandex.ua // 123456
NIMH, DBT applets. Applet password: Qwe123!!!
Users:
prodml1@yandex.com // 123456
bughunterqa123@gmail.com // 123456

Environment:
https://admin.mindlogger.org/
ML Pilot 0.16.17(Android), 0.16.18(iOS)
Samsung Galaxy S7 Edge SM-G935FD // Android 8.0
iPhone XR // iOS 14.3

**Comment by natalia-muzyka** [comment] 2021-09-28 15:37
**The issue is reproducible again on PROD.**
Video: https://www.screencast.com/t/Sn8AxhjBud

Environment:
ML Pilot v0.17.32 
ML v0.17.32
iPhone SE (2020) // iOS 14.2
iPhone 6 Plus // iOS 12.4.8

**Comment by natalia-muzyka** [comment] 2021-09-29 14:17
Notifications still don't work:
Video: https://www.screencast.com/t/vjWBp9smqz2

Environment:
ML Pilot v0.17.32
iPhone SE (2020) // iOS 14.2
Samsung Galaxy S7 SM-G930FD // Android 8.0
owner: loui_ml@protonmail.com // 12345678
user: alyssia_ml@protonmail.com // qwertyuio
applets: NIMH, simple item types
applets password: Qwe123!!!

**Comment by natalia-muzyka** [comment] 2021-09-30 07:16
Verified as fixed.
Video: https://www.screencast.com/t/LSI1BKIz2

Environment:
ML Pilot v0.17.32
iPhone SE (2020) // iOS 14.2
Samsung Galaxy S7 SM-G930FD // Android 8.0
owner: loui_ml@protonmail.com // 12345678
user: alyssia_ml@protonmail.com // qwertyuio
applets: NIMH, simple item types
applets password: Qwe123!!!

**Comment by natalia-muzyka** [comment] 2021-12-22 10:53
@devbtech 
Reproducible on ML Pilot 0.18.21
Video: https://www.screencast.com/t/IVh3xBLj

Environment:
Samsung Galaxy S9	10.0
iPhone 6s	14.4
iPhone 8 Plus	13.3
Samsung Galaxy Tab S6 SM-T865	9.0

account: test-user3@com.us pass:123456789
applet: NIMH
Applet password: Qwe123!!!

**Comment by natalia-muzyka** [comment] 2021-12-22 17:16
@devbtech 
the issue is still reproducible,
video: https://www.screencast.com/t/ceW7FpzYevhZ

Environment:
ML Pilot 0.18.21 prod
Samsung Galaxy S9 10.0
iPhone 6s 14.4
iPhone 8 Plus 13.3
Samsung Galaxy Tab S6 SM-T865 9.0

account: test-user3@com.us pass:123456789
applet: scheduling check, scheduling check (1)

account: kimberly_ml@protonmail.com pass:12345678
applet: DBT(Kimberly) / Target Behaviors
Applet password: Qwe123!!!

**Comment by natalia-muzyka** [comment] 2021-12-28 09:01
Verified as fixed: https://www.screencast.com/t/JoLHbxt1

Environment:
ML Pilot 0.18.21 prod
Samsung Galaxy S9 10.0
iPhone 6s 14.4
iPhone 8 Plus 13.3

**Comment by WorldImpex** [comment] 2022-08-29 10:04
Error is shown when selecting the notification 
![Screenshot_20220827-091340.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/b3cedec7-d2ab-439f-9d75-8d66bbf1ab66)

**Comment by karser** [comment] 2022-09-12 16:21
I re-generated apple certs and fixed provisioning profiles.
Bitrise build is successful.
![image.png](https://images.zenhubusercontent.com/62e92fe4e7d41a51869b6319/e5d757d3-a512-471f-bb5f-9c2632401dc9)

**Comment by natalia-muzyka** [comment] 2022-09-13 09:35
Notifications are not fired on PROD at all.
Video: https://www.screencast.com/t/5bJWxsya2

Environment:
ML Pilot v0.21.48 
Samsung Galaxy Tab S6 SM-T865 // Android  9.0
Apple iPad 9th gen (2021) / iOS 15.5
test-user1@com.us	/ qwerty
applet: aaaa
activity: aaaa
Applet password: Qwe123!!!

**Comment by natalia-muzyka** [comment] 2022-09-15 11:37
Verified as fixed. Notifications work on production.

Video: ![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/b59df706-d432-4df0-9375-26bd33068caf)

Environment:
ML Pilot v0.21.48
Samsung Galaxy Tab S6 SM-T865 // Android 9.0
Apple iPad 9th gen (2021) / iOS 15.5
iPhone 7 // iOS 13.1.1
Google Pixel 5a // Android 11

**Comment by natalia-muzyka** [comment] 2022-10-19 11:32
@karser 
Notifications are not fired on prod. There is 403 and 500 Error after saving the schedule.
Video: https://www.screencast.com/t/XH1cdmM9

Applets: Healthy Brain Network (NIMH), EMA, DBT

cc: @eleonova-scn

**Comment by natalia-muzyka** [comment] 2022-10-19 16:58
Notifications are received. After a more thorough investigation, I found the exact case when notifications don't work. Created a new ticket in JIRA:
https://mindlogger.atlassian.net/browse/MIN-30

The 403 and 500 issue seems to be related to the protocol applets' calendar. 
Created a new ticket in JIRA:
https://mindlogger.atlassian.net/browse/MIN-31

cc: @eleonova-scn

**Comment by natalia-muzyka** [comment] 2022-10-26 07:45
@karser Notifications are not fired on production. Received the last notification on 25/10.

Video: https://www.screencast.com/t/uiXV25iohJ

Environment:
ML Pilot v0.21.54
iPhone 13 // iOS 15.6
Google Pixel 5a // Android 11
demo_test_account@ml.com	/ 123456
applets: DBT, A/B Trails, Stability task touch
Applet password; Qwe123!!!

**Comment by TatianaBessonova** [comment] 2022-10-26 07:53
Reproduced  on production:
Environment:
ML Pilot v0.21.54
iPhone 7 Plus, iOS 14.4.
Google Pixel 3 XL // Android 10
clever8clever08@gmail.com / qwe123!!!
applet: For Web One
Applet password: Qwe123!!!

**Comment by natalia-muzyka** [comment] 2022-10-26 13:47
Verified as fixed. Video: https://www.screencast.com/t/B8IfyiDIoPg

Environment:
ML Pilot v0.21.54
iPhone 13 // iOS 15.6
Google Pixel 5a // Android 11
demo_test_account@ml.com / 123456
applets: DBT, NIMH, EMA, A/B Trails, Stability task touch
Applet password; Qwe123!!!

**Comment by natalia-muzyka** [comment] 2022-11-07 09:51
Notifications are not fired on production. Received the last notification on 05/11.

Video: https://www.screencast.com/t/wQXqBGRx2q2

Environment:
ML Pilot v0.21.54
iPhone 13 // iOS 15.6
Google Pixel 5a // Android 11
demo_test_account@ml.com / 123456
applets: DBT, A/B Trails
Applet password; Qwe123!!!

**Comment by natalia-muzyka** [comment] 2022-11-14 10:39
Verified as fixed on 
ML Pilot v0.21.54 prod
iPhone 7 // iOS 13.1.1
Pixel 4a // Android 13

**Comment by natalia-muzyka** [comment] 2022-11-22 11:25
@karser 
The issue is reproducible again.
Video: https://www.screencast.com/t/q7WT8vdlc

Environment:
ML Pilot v0.21.54
iPhone 13 // iOS 15.6
Google Pixel 4a // Android 13
demo_test_account@ml.com / 123456
applets: DBT, EMA, NIMH
geria.test@gmail.com / 123456
applets: My applet Geria
Applet password; Qwe123!!!

**Comment by natalia-muzyka** [comment] 2022-12-12 08:13
Notifications failed on prod again @karser 

Environment:
ML Pilot v0.21.54
iPhone 7 // iOS 13
Google Pixel 4a // Android 13
natalia.muzyka@qatestlab.net / 19911170
my applet
notifications check

**Comment by natalia-muzyka** [comment] 2022-12-12 10:53
Fixed

Environment:
ML Pilot v0.21.54
iPhone 7 // iOS 13
Google Pixel 4a // Android 13
natalia.muzyka@qatestlab.net / 19911170
my applet
notifications check

**Closed by natalia-muzyka** 2022-12-12 10:53 UTC
Labels: bug, Android, iOS, mobileapp, HotFix
