### ISSUE TITLE
Notificatios are firing multiple times

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-app#898] opened 2020-04-05 22:06 UTC
Steps to Recreate - All steps are done on dev 
1. Create a new manager (sn: manager1) and user account (sn: user2) with password abcd123
2. Upload NIMH applet 
3. Add a group notification for Pre-questionnaire  
4. See results 

Expected Results: Receive one notification from pre-questionnaire. 
Actual Results: Receive two from pre-questionnaire with other random activity notifications 

![IMG_0730](https://user-images.githubusercontent.com/22243307/78511109-2a683d00-7768-11ea-8fc5-37a600c94e94.PNG)

**Comment by sergeysemenuta** [comment] 2020-04-06 12:04
Replicated this issue on dev server.
The group of users has received 4 notifications instead of one 
https://www.screencast.com/t/nrvySjiLYd
iPhone 7 // iOS 11.4.1 // v  v 0.11.21   
Huawei P20 // Android 8.1.0 // v 0.11.21  
iPhone 5s // iOS 12.3.1// v 0.11.21

**Comment by sergeysemenuta** [comment] 2020-04-06 15:38
The issue is actual for all types of notifications. Users are getting multiple notifications for the events

**Comment by sergeysemenuta** [comment] 2020-04-08 12:57
The issue is fixed.
The users are received 1 notification for each event
![IMG_0348.JPG](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/6b329695-959a-46ac-a9f5-e9fc86403205)
Checked on:
Prod server
iPhone 7 // iOS 11.4.1 //  v 0.11.21   
Huawei P20 // Android 8.1.0 // v 0.11.21  
iPhone 5s // iOS 12.3.1// v 0.11.21

Closing the issue.

**Closed by sergeysemenuta** 2020-04-08 12:57 UTC
Labels: bug
