### ISSUE TITLE
Forgot password email does not arrive

### ISSUE THREAD

**Issue by abadioli** [ChildMindInstitute/mindlogger-app#122] opened 2019-03-19 15:19 UTC

**Comment by abadioli** [comment] 2019-03-19 15:54
Arrived after 35 minutes

**Comment by shnizzedy** [comment] 2019-03-19 16:15
Duplicate of https://github.com/ChildMindInstitute/mindlogger-app/issues/122

In my experience, the first few attempts get caught in spam filters. I don't know a good way around that problem.

**Closed** 2019-03-19 16:15 UTC
Labels: Android, bug, iOS

**Comment by shnizzedy** [comment] 2019-03-19 16:19
Duplicate of ChildMindInstitute/mindlogger-app-backend#56

In my experience, the first few attempts get caught in spam filters. I don't know a good way around that problem.

**Comment by abadioli** [comment] 2019-03-19 16:20
I checked - no spam.... they just took a long time arrive

**Comment by shnizzedy** [comment] 2019-03-19 16:22
[Greylisting](https://en.wikipedia.org/wiki/Greylisting)?
